# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='申请内容')),
                ('in_queue', models.BooleanField(default=True, help_text='只要任务没被人处理，就会一直在queue中')),
            ],
        ),
        migrations.CreateModel(
            name='FlowBecome_Full_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probation_start_date', models.DateField(verbose_name='入职日期')),
                ('probation_end_date', models.DateField(verbose_name='转正日期')),
            ],
        ),
        migrations.CreateModel(
            name='FlowLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.SmallIntegerField(choices=[(0, '出差借款')], verbose_name='用途')),
                ('amount', models.PositiveIntegerField(verbose_name='借款金额')),
                ('start_date', models.DateTimeField(verbose_name='用款时间')),
                ('end_date', models.DateTimeField(verbose_name='还款时间')),
            ],
        ),
        migrations.CreateModel(
            name='FlowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '同意'), (1, '拒绝'), (2, '需额外审批人审批'), (3, '待处理')], verbose_name='审批状态')),
                ('comment', models.TextField(max_length=1024, verbose_name='审批意见')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_dynamic_role', models.BooleanField(default=False)),
                ('role_lookup_func', models.CharField(blank=True, max_length=64, null=True, verbose_name='查找动态role的函数')),
            ],
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('flow_type', models.CharField(choices=[('_FlowVaction', '请假流程'), ('_FlowTrip', '出差申请'), ('_FlowBecome_Full_Staff', '转正申请'), ('_FlowLoan', '借款申请')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FlowTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Flow')),
            ],
        ),
        migrations.CreateModel(
            name='FlowVaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaction_type', models.SmallIntegerField(choices=[(0, '病假'), (1, '年假'), (2, '事假'), (3, '产假')], default=2)),
                ('start_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Flow')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='环节名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='环节介绍')),
                ('order', models.PositiveSmallIntegerField(verbose_name='环节步骤')),
                ('is_countersign', models.BooleanField(default=False, verbose_name='会签环节')),
                ('required_polls', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='会签最少需同意的人数')),
                ('flow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.FlowTemplate', verbose_name='所属流程')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.FlowRole', verbose_name='审批角色')),
            ],
        ),
    ]
