# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrole',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flowrecord',
            name='extra_parties',
            field=models.ManyToManyField(blank=True, related_name='related_parties', to=settings.AUTH_USER_MODEL, verbose_name='额外审批人列表'),
        ),
        migrations.AddField(
            model_name='flowrecord',
            name='flow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='audit.Flow'),
        ),
        migrations.AddField(
            model_name='flowrecord',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Step'),
        ),
        migrations.AddField(
            model_name='flowrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批用户'),
        ),
        migrations.AddField(
            model_name='flowloan',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Flow'),
        ),
        migrations.AddField(
            model_name='flowbecome_full_staff',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Flow'),
        ),
        migrations.AddField(
            model_name='flow',
            name='started_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='流程发起人'),
        ),
        migrations.AddField(
            model_name='flow',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.FlowTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('flow_template', 'order')]),
        ),
    ]
