# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20180309_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'verbose_name': '流程总表', 'verbose_name_plural': '流程总表'},
        ),
        migrations.AlterModelOptions(
            name='flowbecome_full_staff',
            options={'verbose_name': '转正流程', 'verbose_name_plural': '转正流程'},
        ),
        migrations.AlterModelOptions(
            name='flowloan',
            options={'verbose_name': '借款申请', 'verbose_name_plural': '借款申请'},
        ),
        migrations.AlterModelOptions(
            name='flowrecord',
            options={'verbose_name': '流程流转记录', 'verbose_name_plural': '流程流转记录'},
        ),
        migrations.AlterModelOptions(
            name='flowrole',
            options={'verbose_name': '流程角色', 'verbose_name_plural': '流程角色'},
        ),
        migrations.AlterModelOptions(
            name='flowtemplate',
            options={'verbose_name': '流程模版', 'verbose_name_plural': '流程模版'},
        ),
        migrations.AlterModelOptions(
            name='flowtrip',
            options={'verbose_name': '出差流程', 'verbose_name_plural': '出差流程'},
        ),
        migrations.AlterModelOptions(
            name='flowvaction',
            options={'verbose_name': '请假流程', 'verbose_name_plural': '请假流程'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': '流程环节', 'verbose_name_plural': '流程环节'},
        ),
    ]
