# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_customers', '可以访问 客户库'), ('crm_table_list', '可以访问 kingadmin 每个表的数据列表页'), ('crm_table_index', '可以访问 kingadmin 首页'), ('crm_table_list_view', '可以访问 kingadmin 每个表中对象的修改页'), ('crm_table_list_change', '可以修改 kingadmin 每个表中对象'), ('crm_table_list_action', '可以操作 每个表的 action 功能'), ('crm_can_access_my_clients', '可以访问 自己的 客户列表'), ('crm_app_tables', '可以访问 所有列表的内容'), ('crm_table_add_view', '可以访问所有列表添加页面'), ('crm_table_add_add', '可以添加所有列表'), ('crm_table_del_view', '可以访问所有列表删除页'), ('crm_table_del_del', '可以删除所有列表'), ('crm_personal_password_reset_view', '访问管理员修改密码页'), ('crm_personal_password_reset', '管理员修改密码'), ('crm_password_reset_view', '访问个人修改密码页'), ('crm_password_reset', '个人修改密码')), 'verbose_name': 'CRM账户', 'verbose_name_plural': 'CRM账户'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='contract_agreed',
            field=models.BooleanField(verbose_name='我已认真阅读完协议并同意全部内容'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='contract_approved',
            field=models.BooleanField(help_text='在审阅无误后勾选此项,合同即生效', verbose_name='审批通过'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='why_us',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='报名理由'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='your_expectation',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='具体期望'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='crm.Role', verbose_name='权限角色'),
        ),
    ]
